### PR TITLE
Migrate gatsby from v1 to v2

### PR DESCRIPTION
**Pull request by kairstenfay**
# Documentation 

I'm following [this guide for upgrading gatsby from v1 to v2](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/). 

## Steps taken
Steps taken (all within `static-site` directory)
1. [Upgrade gatsby version](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/) with `npm i gatsby@latest`

2. [Upgrade gatsby-related packages](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/)
```
npm i gatsby-link@latest gatsby-plugin-catch-links@latest gatsby-plugin-feed@latest gatsby-plugin-google-analytics@latest gatsby-plugin-manifest@latest gatsby-plugin-nprogress@latest gatsby-plugin-offline@latest gatsby-plugin-react-helmet@latest gatsby-plugin-sharp@latest gatsby-plugin-sitemap@latest gatsby-plugin-styled-components@latest gatsby-plugin-twitter@latest gatsby-remark-autolink-headers@latest gatsby-remark-copy-linked-files@latest gatsby-remark-images@latest gatsby-remark-prismjs@latest gatsby-remark-responsive-iframe@latest gatsby-remark-smartypants@latest gatsby-source-filesystem@latest gatsby-transformer-remark@latest
```

3. [Install react](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#install-react) with `npm i react react-dom`

4. [Install plugins' peer dependencies](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#install-plugins-peer-dependencies)
```
npm install --save gatsby-plugin-react-helmet react-helmet gatsby-plugin-styled-components styled-components babel-plugin-styled-components
```

5. [Change modifyWebpackConfig to onCreateWebpackConfig](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#change-modifywebpackconfig-to-oncreatewebpackconfig). 

_edit (james 2020-01-15): see below for current status_

### CODE REVIEW

**Comment by jameshadfield** [comment]
@kairstenfay -- upgrade node & npm and this will work*. I resolved this by upgrading to versions 13.6.0 & 6.13.6 respectively, removing `node_modules` and the lock file, and reinstalling via `npm i`.

*There are other build errors, but these look like they are covered in the gatsby upgrade guide.

**Comment by kairstenfay** [comment]
> @kairstenfay -- upgrade node & npm and this will work*. I resolved this by upgrading to versions 13.6.0 & 6.13.6 respectively, removing `node_modules` and the lock file, and reinstalling via `npm i`.
> 
> *There are other build errors, but these look like they are covered in the gatsby upgrade guide.

Thanks, James. Upgrading to node v13 plus removing `node_modules` and `package-lock.json` worked for me.

**Comment by jameshadfield** [comment]
Update: The site now builds using gatsby v2 but there are a number of issues:

* Styling is really bad -- this is likely due to https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#remove-or-refactor-layout-components and shouldn't be too hard to fix if so.
* The react warnings in the console are due to `react-helmet` -- we can either wait for a fix or switch to `react-helmet-async` (or drop it, I'm not sure if it's needed for us)

**Comment by trvrb** [comment]
Awesome! I poked around the site for a little while and the only bug I was able to find was the 404 bug noted above.

**Comment by trvrb** [comment]
I believe that Python 2.7 is no longer required for this Gatsby installation. Or that was my experience installing now on a system that lacks `python2` command. I've updated the readme accordingly in the commit below, but please feel free to revert is this update was in error.

Generally, my install experience on this branch is much improved. Various Gatsby plugins had been giving me trouble before.

The only bug I've found is the 404 issue.

**Comment by trvrb** [comment]
I decided to merge this to ease development. I believe the only issue that needs resolving is the 404 not behaving as intended.

**Pull request merged**
