### PR TITLE
Add CAMES build to Nextstrain Community build repository.

### PR DESCRIPTION
**Pull request by AlbertRockG**
## Description of proposed changes

The objective of this is to keep the scientific community updated regarding the circulating SARS-CoV-2 strains in the countries part of the African and Malagasy Council of Higher Education (CAMES) for the Also-Covid-19 Project. It will be updated when needed.

Our GitHub repository is https://github.com/AlbertRockG/ncov-cames

Please, do let me know if there are any suggestions. Thanks

### CODE REVIEW

**Comment by victorlin** [comment]
Hi @AlbertRockG, thank you for opening this PR! We welcome your contribution.

I noticed your Auspice JSON file is large (164MB), so I suggest minify-ing it for a faster experience. The 164MB file can be minified to 9MB. To do this, you can apply the `--minify-json` option to `augur export`. There are [plans](https://github.com/nextstrain/augur/issues/1331) to automatically minify large JSONs, but for now you have to add it to your command.

Alternatively, you can minify the existing JSON using something like [this](https://stackoverflow.com/a/61125014):

```sh
python -c 'import json, sys;json.dump(json.load(sys.stdin), sys.stdout)' < ncov-cames_CAMES.json > ncov-cames_CAMES-new.json
rm ncov-cames_CAMES.json
mv ncov-cames_CAMES-new.json ncov-cames_CAMES.json
```

**Review by victorlin — APPROVED** [review]

**Comment by AlbertRockG** [comment]
Thank you, @victorlin!

**Comment by victorlin** [comment]
@AlbertRockG I have another suggestion: in [auspice_config_cames.json](https://github.com/AlbertRockG/ncov-cames/blob/1e4813a97ff0274dbe76735ea470fb286fc540d7/cames_profile/auspice_config_cames.json), use `"build_url": "https://github.com/AlbertRockG/ncov-cames"`. This would be more consistent with the other community builds which link to GitHub repositories. It would change from the first image to the second image:

build_url

<br>
<br>

build_url_new

<br>
<br>

The CAMES website link would still be appropriate in [description_cames.md](https://github.com/AlbertRockG/ncov-cames/blob/master/cames_profile/description_cames.md).

**Comment by AlbertRockG** [comment]
Thank you very much for this suggestion, @victorlin. I've been pondering about it, whether I should remove it or not, and your advice enlightened me. Thanks once again. 
I want to inform @tsibley that, with your help, I succeeded to minify my JSON file.

**Comment by victorlin** [comment]
@AlbertRockG you're very welcome! Glad to see your build on the community page.

**Pull request merged**
