### PR TITLE
Use "href" template literals for safe-by-construction URL strings

### PR DESCRIPTION
**Pull request by tsibley**
Avoids having to write out encodeURIComponent(), which is quite a mouthful!

### Testing

- [x] Checks pass

### CODE REVIEW

**Comment by tsibley** [comment]
In [discussion in Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1682624875485889), @joverlee521 suggested `uri` instead of `href`. I'd be fine with this name too.

**Comment by tsibley** [comment]
`uri`'s probably better, even if `href` feels cuter to me.

**Review by joverlee521 — APPROVED** [review]
I recommend adding a link to some tagged template docs (e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates). 

I definitely had no idea how the function worked the first time I read through it.

**Comment by tsibley** [comment]
@joverlee521 Fair enough! I added comments and [repushed](https://github.com/nextstrain/nextstrain.org/compare/ac052ed19a347e0c8e1d551e756db8d0f416da7b..63da24bd5a2ad648b1f3ad396e5f20c1604c93e3).

**Pull request merged**
