### PR TITLE
SARS-CoV-2 Forecasts

### PR DESCRIPTION
**Pull request by joverlee521**
### Description of proposed changes
Adds a Gatsby page for SARS-CoV-2 forecasts that describes the forecast models and displays the static images of plots generated by the [forecasts-ncov pipeline](https://github.com/nextstrain/forecasts-ncov) (not yet implemented). 

The display of static images is expected to be temporary as we will develop interactive visualizations for modeling results. 

### TODOs
- [x] replace placeholder texts (@trvrb)
- [x] replace placeholder images

### CODE REVIEW

**Comment by jameshadfield** [comment]
P.S. [Latest CI failure seems transient](https://github.com/nextstrain/nextstrain.org/actions/runs/3753746737/jobs/6377289786)

**Comment by jameshadfield** [comment]
Rebased onto master & updated to use figures produced from https://github.com/nextstrain/forecasts-ncov/pull/8.

@joverlee521 I didn't change your React design here much at all - i'll leave this up to you if you wish to make any modifications since we're only using {gisaid, global} to start with.

The image URLs will need updating once we have images present at a stable "latest" endpoints, but I added trial URLs here to see how things would look.

**Comment by joverlee521** [comment]
Additional TODOs from internal review on [Slack](https://bedfordlab.slack.com/archives/C036L7V615F/p1672798218620909):

- [ ] remove "Data Provenance" and "Geo-Resolution" buttons
- [ ] reorder the 4 sections to match the interactive viz (related to https://github.com/nextstrain/forecasts-ncov/issues/14)
- [ ] expand 4 sections by default

**Review by jameshadfield — APPROVED** [review]
Thanks @joverlee521 for the finishing touches! Everything looks good. As discussed in yesterday's meeting I'm going to update the viz app (vendored via `git subtree`) and merge this so that this is available on canary 🚀

**Comment by jameshadfield** [comment]
Not sure what's going on with Heroku's review apps, as I cannot see this PR there to re-deploy it. Have tested locally.

**Pull request merged**
