### PR TITLE
docs: Production requirements

### PR DESCRIPTION
**Pull request by tsibley**
Motivated by our work with CDC for them to be able to internally host nextstrain.org, but this documentation will also be useful for ourselves.

We can adapt/amend it later to account for any "Nextstrain Groups Server" (i.e. just the Groups bits of nextstrain.org) that we end up creating.

Related-to: <https://github.com/nextstrain/private/issues/94>

## Checklist

- [x] [Preview of page](https://nextstrain--737.org.readthedocs.build/projects/nextstrain-dot-org/en/737/production.html) looks good
- [x] Checks pass

### CODE REVIEW

**Review by victorlin — APPROVED** [review]
Read through the preview - looks good. I don't know much about some topics such as reverse proxy, Redis sessions, OAuth 2.0 clients, and CA certificates, so I can't say much about those contents besides that it seems comprehensive and I can see it being a useful resource to understand what's required.

There's still a gap in documenting how these are configured for our actual nextstrain.org instance, but that's beyond this PR.

**Comment by tsibley** [comment]
This is based on https://github.com/nextstrain/nextstrain.org/pull/733 so I'll wait for that to merge before merging this.

**Comment by tsibley** [comment]
> There's still a gap in documenting how these are configured for our actual nextstrain.org instance, but that's beyond this PR.

True, there's not documentation of our actual deployment structured like this new page, but most of these bits are documented somewhere. The [infrastructure page](https://docs.nextstrain.org/projects/nextstrain-dot-org/en/latest/infrastructure.html) at least mentions many of them. The [sessions page](https://docs.nextstrain.org/projects/nextstrain-dot-org/en/latest/sessions.html) discusses Redis in that context too. The Terraform configurations and corresponding config files also detail specifics.

**Comment by tsibley** [comment]
> This is based on #733 so I'll wait for that to merge before merging this.

Actually, since I'm making a few minor fixups to #733, I'll first merge this into that (and then that into `master`).

**Pull request merged**
