### PR TITLE
Show GitHub account avatar on community tiles

### PR DESCRIPTION
**Pull request by victorlin**
[_preview_](https://nextstrain-s-victorlin--c1t8eq.herokuapp.com)

## Description of proposed changes

This is more consistent with the Nextstrain Groups tiles showing the group's personalized logo.

## Related issue(s)

- #934

## Checklist

- [x] [Preview](https://nextstrain-s-victorlin--c1t8eq.herokuapp.com) looks good
- [x] Checks pass
- [x] Check if changes affect the [resource index JSON revision](https://docs.nextstrain.org/projects/nextstrain-dot-org/en/latest/resource-collection.html#resource-index-revisions)

### CODE REVIEW

**Comment by genehack** [comment]
Doesn't seem to work as intended for organizations? Compare the Chikungunya tile and the small generic icon there with what's on [the Vienna RNA org](https://github.com/viennarna). Whereas the Yersina pestis build does show the same icon as [ktmeaton's Github](https://github.com/ktmeaton). 

I would also consider relocating the mini-icon overlay from the top left of the tile to near the bottom left, to the left of and top-aligned with the title/caption text. I think it will be more noticeable and having the attribution next to the title feels appropriate. (Suggestion only, no strong opinion really.)

**Comment by victorlin** [comment]
> Doesn't seem to work as intended for organizations? Compare the Chikungunya tile and the small generic icon there with what's on [the Vienna RNA org](https://github.com/viennarna). Whereas the Yersina pestis build does show the same icon as [ktmeaton's Github](https://github.com/ktmeaton).

The ViennaRNA tile is for a Nextstrain Groups resource which is not affected by the changes here. It won't work on PR review apps due to AWS permissions, but you can see it on https://next.nextstrain.org

> I would also consider relocating the mini-icon overlay from the top left of the tile to near the bottom left, to the left of and top-aligned with the title/caption text. I think it will be more noticeable and having the attribution next to the title feels appropriate. (Suggestion only, no strong opinion really.)

Could you provide a mockup? I'm confused on what "top-aligned with the title/caption text" means, and what I'm visualizing seems to be opposite of "having the attribution next to the title".

**Comment by joverlee521** [comment]
> I would also consider relocating the mini-icon overlay from the top left of the tile to near the bottom left, to the left of and top-aligned with the title/caption text. I think it will be more noticeable and having the attribution next to the title feels appropriate. (Suggestion only, no strong opinion really.)

The mini-icons were placed over the main image to avoid issues with title widths ([Slack context](https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1718412436850759?thread_ts=1718403195.109039&cid=C7SDVPBLZ))

**Review by trvrb — APPROVED** [review]

**Comment by trvrb** [comment]
I definitely like the personalized avatars (for GitHub and for Groups).

**Review by joverlee521 — APPROVED** [review]

**Review by tsibley — APPROVED** [review]

**Comment by genehack** [comment]
> Could you provide a mockup? I'm confused on what "top-aligned with the title/caption text" means, and what I'm visualizing seems to be opposite of "having the attribution next to the title".

This is an extremely rough mockup; pretend I did the extra work to remove the logo at top left:

Screenshot 2024-07-30 at 12 11 26

May not be worth the extra hassle of dealing with the spacing around the title/caption being center-aligned but I think this makes the logo more apparent; some of the titles because of how colorful they are; the icon gets visually lost.

**Comment by victorlin** [comment]
Thanks! I prefer the current placement, but happy to consider your alternative if others also express preference for it.

Note that one of the requirements of the featured analyses is that [descriptions take up at most 2 lines](https://github.com/nextstrain/nextstrain.org/blob/ad0478b85ec6a2e05288dbcf3730602450537dff/static-site/content/featured-analyses.yaml#L4-L5). The alternative placement would reduce the amount of space available for description text which would require rewording some existing tiles such as:

image

Or we could make the tiles bigger, but I think any bigger might be too big.

**Pull request merged**
