### PR TITLE
Build listing UI improvements

### PR DESCRIPTION
**Pull request by eharkins**
### Description of proposed changes    
As discussed in various issues listed below, on slack, and in nextstrain meetings, the list of sars-cov-2 builds is getting rather long and would benefit from changes to the interface to make it take up less space and allow you to get the build you are looking for (or just browse) more effectively and faster. 

This is just a start which steals the collapsing-menu code from the sit-reps listing directly below the builds listing on the same page, but already saves a decent chunk of space (I added some duplicate builds to fill out a row):
Screen Shot 2020-11-24 at 4 53 09 PM

I wanted to just create this PR so that we can get some 👍  or 👎  before taking it further in any particular direction. 

I also thought it would be worth mentioning that if all we wanted was a collapsible listing like this, read the docs does this pretty well as part of their table of contents, so we could just move such listings into a top-level docs heading at docs.nextstrain.org or a separate read the docs project (you could imagine builds.nextstrain.org or something like that).

### Related issue(s)  
#62 
#180 
#182 
#206 

### Testing
Locally with gatsby

### CODE REVIEW

**Comment by eharkins** [comment]
Also want to note that the code used to do this can be abstracted out better so that it may be reused for listing builds for different pathogens. Just waiting to do that until we were closer to choosing a particular approach (although these things can probably happen at the same time).

**Comment by emmahodcroft** [comment]
I like how this is developing - the layout is more compact and being able to collapse regions really helps to get an overview and just focus on whatever part you want to focus on!

Just a couple of suggestions off the top of my head: The expand/collapse animation is a bit too slow for me - if you are clicking through a number of EU countries or US states, it gets a little irritating. 

I also wonder if an 'expand all' for some categories - like Europe or USA states might be useful? If I imagine I'm going to be clicking between many different EU countries for example, I may want to just expand them all so I can click around more easily. We probably wouldn't want that for, say, all builds in all regions, though - just some 'subsections' (I hope that makes sense!).

**Comment by eharkins** [comment]
@emmahodcroft thanks for the feedback!

9551913 addresses:
1. the animation time; this should be much faster
2. the collapsible menu problem; since we use a javascript library to make these menus, it would be non-trivial to make a collapse / expand all feature. If this is important, we can certainly make it happen, but instead I am trying a simple approach of just auto-expanding menus when it seems reasonable to do so (i.e. when there are fewer than 5 dropdowns at that same level - since e.g. expanding all countries in Europe might be overkill). Hopefully between this and reducing the animation time, the overall experience is improved to make an expand-all less necessary; there are definitely other improvements to make that might help with this general goal of more quickly navigating these menus both in cases where you are looking for something particular and just browsing.

**Comment by eharkins** [comment]
Some styling improvements still to come here as well.

**Comment by emmahodcroft** [comment]
>the collapsible menu problem; since we use a javascript library to make these menus, it would be non-trivial to make a collapse / expand all feature. If this is important, we can certainly make it happen, but instead I am trying a simple approach of just auto-expanding menus when it seems reasonable to do so (i.e. when there are fewer than 5 dropdowns at that same level - since e.g. expanding all countries in Europe might be overkill). Hopefully between this and reducing the animation time, the overall experience is improved to make an expand-all less necessary; there are definitely other improvements to make that might help with this general goal of more quickly navigating these menus both in cases where you are looking for something particular and just browsing.

Thanks for clarifying Eli, that makes sense! I hadn't thought about this from a computational point of view!

**Pull request merged**
