### PR TITLE
update logos to reflect current funding sources in Basel

### PR DESCRIPTION
**Pull request by rneher**
### Description of proposed changes    
This PR removes logos of MPG and ERC which haven't funded nextstrain in the last 5 years. This adds SIB and the University of Basel logo.

### CODE REVIEW

**Comment by emmahodcroft** [comment]
This looks good!

**Comment by tsibley** [comment]
Noting that the footer for [docs.nextstrain.org](https://docs.nextstrain.org) will also want updating: https://github.com/nextstrain/sphinx-theme/blob/main/lib/nextstrain/sphinx/theme/footer.html

**Comment by rneher** [comment]
thanks for noting the necessary changes in the docs theme. I (attempted to) implemented them in the above PR.

**Comment by rneher** [comment]
this seems to deploy fine, can we merge this?

**Comment by tsibley** [comment]
Fine by me! I didn't intend to block merge/deploy with my earlier comment about the theme; apologies if that wasn't clear.

**Pull request merged**
