### PR TITLE
making the oropouche build live and adding it to the splash page

### PR DESCRIPTION
**Pull request by miparedes**
## Description of proposed changes

Adding in changes to make the oropouche build live and featured on the Nextstrain splash page. 
- added oropouche to routing, manifest, and added a tile and card. 
- Not sure if anything else is missing? 

- [ ] Checks pass
- [ ] Check if changes affect the [resource index JSON revision](https://docs.nextstrain.org/projects/nextstrain-dot-org/en/latest/resource-collection.html#resource-index-revisions)

### CODE REVIEW

**Comment by miparedes** [comment]
Is there a way to test that it all looks right?

**Comment by jameshadfield** [comment]
> Is there a way to test that it all looks right?

You can use the review app (click "view deployment" above) and see the [tile on the main page](https://nextstrain-s-adding-oro-fqt00m.herokuapp.com/) - I think the dimensions of the added image aren't right:

image

It's not showing on /pathogens for some reason... (I'll try to build locally and debug):

image


And [/oropouche](https://nextstrain-s-adding-oro-fqt00m.herokuapp.com/oropouche) redirects to /oropouche/L, but that 404s because you haven't yet uploaded the JSONs to the nextstrain-data bucket.

**Review by jameshadfield — CHANGES_REQUESTED** [review]
Testing locally:

- [ ] The added image should be 250 x 250px (It's currently 1908 x 1278)
- [ ] The datasets aren't yet on the `nextstrain-data` S3 bucket, which is why the links 404, however the manifest / routing changes look correct.

The missing tile on /pathogens is because oropouche datasets are not yet indexed. Once they're on the `nextstrain-data` S3 bucket they'll be indexed in the next ~48 hours and then they'll appear here. This isn't blocking for merge.

**Comment by trvrb** [comment]
I just ran "Phylogenetic" GitHub Action here: https://github.com/nextstrain/oropouche/actions/runs/11037036241. Dataset URLs in the PR now work as expected: https://nextstrain-s-adding-oro-fqt00m.herokuapp.com/oropouche/.

**Comment by miparedes** [comment]
> Testing locally:
> 
> * [x]  The added image should be 250 x 250px (It's currently 1908 x 1278)
> * [ ]  The datasets aren't yet on the `nextstrain-data` S3 bucket, which is why the links 404, however the manifest / routing changes look correct.
> 
> The missing tile on /pathogens is because oropouche datasets are not yet indexed. Once they're on the `nextstrain-data` S3 bucket they'll be indexed in the next ~48 hours and then they'll appear here. This isn't blocking for merge.

The new commit and the push that @trvrb made to the S3 bucket should resolves these! I also reviewed the testing app and everything seems to look good

**Review by jameshadfield — APPROVED** [review]

**Comment by trvrb** [comment]
Looks great!

**Pull request merged**
