### PR TITLE
Influenza page

### PR DESCRIPTION
**Pull request by eharkins**
see commit messages. WIP

many commits here should go in separately as #266 but this is a separate concept so I used `master` as the base branch in anticipation of that getting merged first.

### CODE REVIEW

**Comment by eharkins** [comment]
Check out https://nextstrain-s-influenza--0koet5.herokuapp.com/influenza/ if you want to see the page.

**Comment by trvrb** [comment]
Awesome! Some quick notes here @eharkins.

- https://clades.nextstrain.org/ is SARS-CoV-2-specific at the moment. I think it will work for flu soon enough, but I'd drop this link for now.
- Likewise I think I'd drop "Nextstrain discussion forum" and "Developer contributions". The SARS-CoV-2 page is a bit special. I think generally these pages want to be pretty streamlined for the pathogen of interest.
- The current setup with the carats requires a lot of clicking to get to pages of interest (especially for seasonal flu). My inclination here would be to start with everything expanded. Easy to scroll and find the thing of interest. This should work for influenza where the list isn't too long. I see how this wouldn't work for SARS-CoV-2.
- The "Nextstrain Team" doesn't work as a link. I'm not sure if this was intentional? This is the case here and with the SARS-CoV-2 page.

I really like where this is headed. That said, I do think we eventually want a "flatter" dataset UI (a little like https://github.com/nextstrain/nextstrain.org/issues/62 that I keep linking to). Something with columns for "maintainer" and "URL" and includes icon like what would be displayed in the byline. And then these columns could be sorted. Or the whole table could be filtered. Or another thought would be something like the GitHub UI here https://github.com/blab. Where each dataset gets its own line that could include title, maintained by, last updated, etc... And most the interaction is through the filter box. The "nested" approach here works for the very hierarchical flu datasets, but I don't think it would work as well for a grab bag of different pathogens from across core builds and different groups. It would be fun to sit down and sketch out some designs at some point.

**Comment by eharkins** [comment]
Thanks for the quick review @trvrb!

Added some commits to address the bullet points. The last one is actually a bug also live on https://nextstrain.org/sars-cov-2 introduced by me forgetting to remove some fields in #248. There isn't meant to be a link there (unless you think we should link somewhere) for Nextstrain Team. I'll fix this separately for that yaml since it's live.

As for the general direction, I added an agenda point to discuss this more in our meeting tomorrow.

**Comment by trvrb** [comment]
Looks great Eli!

**Review by trvrb — APPROVED** [review]

**Comment by joverlee521** [comment]
Is the Nextstrain.org splash page going to link to the new `/influenza` page? (Sorry if I missed the discussion on this.)

Currently the splash page has two flu cards under "Explore Pathogens" (1 for seasonal flu and 1 for avian flu) that link directly to default builds. Should these be combined into one "Influenza" card that links to this new `/influenza` page?

**Comment by eharkins** [comment]
That would make sense to me @joverlee521, thanks I hadn't considered it in this PR. Does that sound good @trvrb?

**Comment by eharkins** [comment]
Checklist before we can merge this:

- [ ] Add a seasonal-influenza-specific intro sentence [here](https://github.com/nextstrain/nextstrain.org/pull/271/files#diff-1535f5e3cb30bdb6a0cded9bd69a2c5abfd75c86c43f87633c7b43efc8b05e34R21). cc @huddlej I can add it if you send it to me on slack.
- [ ] Merge #266 
- [ ] Decide if we want to change flu links on main splash page as Jover points out above and implement those changes.

**Comment by eharkins** [comment]
I merged #278 and #279 here so we can get ready to merge this. However, this contains everything from #266, which I see as distinct in scope from this PR (though this PR relies on some of the refactoring in 266), so I think we need to decide if we still want the what's in #266 (see below) and if so, re-open it and merge it separately. If not, we can remove those commits from this branch before we merge. Details:

#266 includes:
- A script fetching the sars-cov-2 datasets in the manually-curated YAML build catalogue in order to collect metadata (e.g. last updated date) about them.
- A corresponding github action to push this "augmented" YAML with metadata to s3
- Updating the existing /sars-cov-2 page UI to get the above "augmented" YAML from s3 and display dataset metadata
- Extending the infrastructure that creates the database behind https://nextstrain.org/search/sars-cov-2 to include groups,  community builds (listed in the manually-curated YAML build catalogue) in those search results.
- some refactoring of react components behind /sars-cov-2

This PR includes:
- all of the above commits from #266 
- more refactoring of react components behind /sars-cov-2 and /influenza
- creating /influenza page, filterable UI, populated by script to get datasets from s3, github action to run said script

**Comment by eharkins** [comment]
I rebased to remove everything in #266 from this PR, with the exception of necessary component refactoring:
> A script fetching the sars-cov-2 datasets in the manually-curated YAML build catalogue in order to collect metadata (e.g. last updated date) about them.

> A corresponding github action to push this "augmented" YAML with metadata to s3

> Updating the existing /sars-cov-2 page UI to get the above "augmented" YAML from s3 and display dataset metadata

> Extending the infrastructure that creates the database behind https://nextstrain.org/search/sars-cov-2 to include groups, community builds (listed in the manually-curated YAML build catalogue) in those search results.

So now this represents a more well-defined scope:
- refactoring of react components used for /sars-cov-2 for use in /influenza and beyond
- addition of /influenza

Will do some more testing to make sure this is good to go, and will merge locally when it's ready to resolve the conflict github is warning us about.

**Comment by eharkins** [comment]
@jameshadfield can you confirm that you no longer get the [scroll anchor bug](https://github.com/nextstrain/nextstrain.org/pull/279#discussion_r587841678)?

**Review by jameshadfield — APPROVED** [review]
This looks good to me! Can confirm that the scroll bug is no longer. I think a 5min cadence for the catalogue update isn't problematic at the moment, but we should consider how this works in detail in future work around the catalogue. 

I'm in favor of merging this as-is, and I'll start to create issues for future bits of work that are made possible because of this. Thanks @eharkins!

**Comment by trvrb** [comment]
Thanks Eli! Things look generally great. Moving Dataset / Contributor / Uploaded date above the scroll area was smart.

The tick could be increased to 15 minutes. Doesn't matter much for flu whether it's 5 minutes or 24 hours (will get the same thing every time with the exception of slightly modified upload dates). Mostly will matter once we start incorporating groups. Just don't want to have a process that takes longer than 5 minutes (or whatever) to update. I'm fine starting with 5 minutes and seeing if it needs adjusting.

My only remaining issue (and something that doesn't block merge but should get some thought) is the text:

>_Influenza builds_
>This section is an index of public Nextstrain builds (datasets) for flu, organized by type. See here for more information on what a build is. If you know of a build not listed here, please let us know! Please note that inclusion on this list does not indicate an endorsement by the Nextstrain team.

As the linked doc page explains:
>Nextstrain’s focus on providing a real-time snapshot of evolving pathogen populations necessitates a reproducible analysis that can be rerun when new sequences are available. The individual steps necessary to repeat analysis together comprise a “build”.
I think of a "build" as a workflow. `seasonal-flu` is a build. `ncov` is a build. I think of the products produced by these builds (eg `ncov_global.json`) as "datasets". One build may produce multiple datasets. Perhaps this makes the most sense when encountering Auspice JSONs like `ncov_global_2020-06-01` where it's clear this a "dataset" distinct from the ongoing day-to-day rebuilds.

I was thinking of this interface as surfacing "datasets", because we might well have situations like https://nextstrain.org/groups/epicovigal/ncov/galicia-in-progress that don't have an obvious associated "build" (at least one that's not publicly up on GitHub).

**Pull request merged**
