### PR TITLE
Update manifest with dengue gene datasets

### PR DESCRIPTION
**Pull request by j23414**
## Description of proposed changes

Per user request, update dengue builds to include E genes as well as whole genome.

## Related issue(s)

* https://github.com/nextstrain/dengue/issues/17 

## Checklist

- [ ] Checks pass

### CODE REVIEW

**Comment by j23414** [comment]
Merging, since Dataset dropdown options look correct:

* https://nextstrain-s-dengue-man-th1myu.herokuapp.com/dengue/all/E

**Comment by jameshadfield** [comment]
From reading through the changes here, URLs such as "https://nextstrain.org/dengue/denv1" will now be redirected to "https://nextstrain.org/dengue/denv1/genome". On the live site (which doesn't yet have the changes in this PR) both URLs are valid and return the same dataset, so I presume this is deliberate and part of a migration of URLs to the new format?

**Comment by j23414** [comment]
Thanks for checking in! This is intentional; I've uploaded files such as `dengue_denv1_genome.json` with the intention of removing the original `dengue_denv1.json` files within the next week or month.

Feel free to suggest alternative approaches to display both "genome" and "E" in the Dataset dropdown menu, or on the site. It's quite possible I've missed some preferred route for this or am misunderstanding something.

**Comment by jameshadfield** [comment]
This is the best way - auspice doesn't handle mixed levels like  `.../A` + `.../A/B` well. Just wanted to make sure this path was intentional!

**Pull request merged**
