### PR TITLE
CI: Build Auspice client

### PR DESCRIPTION
**Pull request by victorlin**
### Description of proposed changes

It can be useful to test that a newer Auspice version builds properly in the context of this project.

### Related issue(s)

Testing scenario brought up by @jameshadfield in https://github.com/nextstrain/auspice/pull/1520#discussion_r985331370.

### Testing

- [ ] Checks pass

### CODE REVIEW

**Comment by jameshadfield** [comment]
This should be covered by our normal CI (`npm run build` will build the auspice client), right?

The scenario I brought up is where we want to try to build a specific (new / development) version of auspice within the nextstrain.org repo. This requires something along the lines of `npm install nextstrain/auspice#commit` (you can do it locally with `npm link` but I find it more robust to use a github commit). I think the way to achieve this is for an auspice action to make a testing PR within nextstrain.org (i.e. https://github.com/nextstrain/auspice/pull/1565). Perhaps I'm missing something here.

**Comment by victorlin** [comment]
> This should be covered by our normal CI (`npm run build` will build the auspice client), right?

@jameshadfield oh you're right! This PR isn't needed then. Yes, https://github.com/nextstrain/auspice/pull/1565 should be sufficient.

**Comment by tsibley** [comment]
I'd still +1 this though: [b057b77](https://github.com/nextstrain/nextstrain.org/pull/599/commits/b057b77d285ab254a03f614e0beaeb875b79372c)

**Comment by victorlin** [comment]
@tsibley oh I forgot about that! Done with #601

**Pull request closed without merging**
