### PR TITLE
Make group tiles expandable

### PR DESCRIPTION
**Pull request by victorlin**
[_preview_](https://nextstrain-s-victorlin--rgwhw6.herokuapp.com/groups)

## Description of proposed changes

ExpandableTiles is already used in two other places where tiles are used. Use it here too for consistency.

## Related issue(s)

https://github.com/nextstrain/nextstrain.org/issues/947

## Checklist

- [ ] Checks pass
- [ ] [Preview](https://nextstrain-s-victorlin--rgwhw6.herokuapp.com/groups) looks good
- [x] Check if changes affect the [resource index JSON revision](https://docs.nextstrain.org/projects/nextstrain-dot-org/en/latest/resource-collection.html#resource-index-revisions)
- [ ] Merge base PR #950

### CODE REVIEW

**Comment by jameshadfield** [comment]
Looks nice (didn't test with private groups). If we want to keep the current design (or at least make minimal changes), making the cards a more similar size to those on /pathogens would be nice. Longer term I think it's still an open question about what UI we should display above the fold on the /groups page.

**Comment by victorlin** [comment]
> making the cards a more similar size to those on /pathogens would be nice

Done: f8122d1b6b5b63d4f4e007a9f87e6ba28c1094a3

**Review by jameshadfield — APPROVED** [review]

**Review by joverlee521 — APPROVED** [review]
Definitely much cleaner to have the expandable tiles! 

A couple of non-blocking notes

1. The [Groups docs](https://docs.nextstrain.org/en/latest/learn/groups/index.html#names) state the group name can have 3-50 characters. We should probably ensure 50 character group names will still be displayed "nicely" in the smaller tiles.

2. To me, it feels like we are preferentially displaying the groups in the first row. Others may or may not feel the same. Might seem less biased if we note that groups are listed in the order they were added? (The order comes from the order in the groups.json, which is roughly the order in which groups are added.)

**Comment by victorlin** [comment]
Good points!

1. I just tested on the longest group name at 29 characters. It's slightly cut off:

    image

    I've [force-pushed](https://github.com/nextstrain/nextstrain.org/compare/f8122d1b6b5b63d4f4e007a9f87e6ba28c1094a3..20e88d780ef737f21993c23a895a5557d3aa1894) to reduce the left padding so it now looks like this:

    image

    Going forwards, we can check PR previews and update the styles if necessary.

2. I'll make a separate issue for this

**Pull request merged**
